#!/bin/bash

brightness_step=5
notification_timeout=2000


# Uses regex to get brightness from xbacklight
function get_brightness {
    light | grep -Po '[0-9]{1,3}' | head -n 1
}


function notify { 
brightness=$(get_brightness)
icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
if [  "$brightness" = "6" ]; then
    bar=$(seq -s "─" $(($brightness)) | sed 's/[0-9]//g')
    notify-send.sh "$brightness""      ""$bar" -i "$icon_name" -h int:value:"$brightness" -h string:synchronous:"$bar" --replace=555 -t $notification_timeout

    else
        if [ "$brightness" -ge "6" ]; then
    bar=$(seq -s "─" $(($brightness/5)) | sed 's/[0-9]//g')
    notify-send.sh "$brightness""      ""$bar" -i "$icon_name" -h int:value:"$brightness" -h string:synchronous:"$bar" -t $notification_timeout --replace=555
            fi
        fi
}

case $1 in
    up)
    # Increases brightness and displays the notification
    brightnessctl set $brightness_step%+ > /dev/null
    notify
    ;;

    down)
    # Decreases brightness and displays the notification
    brightnessctl set $brightness_step%- > /dev/null
    notify
    ;;

esac
